"""MSP-B0 / AT-636 — deterministic event-signature construction.

An operational event's ``event_signature`` is a stable, deterministic fingerprint
of *which recurring operational event this is* — independent of the exact moment
it occurred or the per-occurrence record id. Two occurrences of the same
recurring event (same provider family, same event kind, same resource) produce
the **same** signature (T2-AC1); two genuinely different events produce
**different** signatures (T2-AC2). This is the join key downstream dedup,
recurrence detection, and hotspot correlation are built on.

What the signature deliberately IGNORES
----------------------------------------
* ``observed_at`` / ``source_timestamp`` — the same event recurring over time
  must collapse to one signature, so time is never a component.
* ``signal_id`` — a per-occurrence id would make every occurrence unique,
  defeating recurrence detection.
* ``severity`` — the same recurring fault may escalate/de-escalate in severity
  between occurrences; folding severity in would fragment a single recurring
  event into several. Severity is carried on the event, not in its identity.
* ``message`` and free-form ``payload`` (except the explicit discriminators the
  per-class rule names, e.g. the ``principal`` for access/audit events).

Construction rules (the mapping contract — T2-AC3)
--------------------------------------------------
The signature is ``"{VERSION}:{sha256_128bit_hex}"`` over an ordered list of
canonical components joined by a unit-separator. The components are chosen by two
axes, so the rule is genuinely *per event class and per provider family*:

* **Provider family** (``aws`` | ``azure`` | ``event_bridge`` | ``generic``,
  resolved from ``source_system``) governs how the provider-native
  ``event_type`` is normalised — AWS event names are space-delimited titles
  (``"EC2 Instance State-change Notification"``), Azure operation ids are slash
  paths (``"Microsoft.Compute/virtualMachines/write"``), the bridge forwards an
  already-canonical token. Each family folds its native spelling to one canonical
  form so the same event named the provider's way always hashes identically.
* **Event class** governs which discriminators participate (see
  :data:`_CLASS_RECIPE`). Every class includes the event-type and the resource
  the event concerns; ``access``/``audit``/``security`` additionally include the
  acting ``principal`` because the same action by two different principals is two
  different events.

Every signature always begins with ``(provider_family, event_class,
resource_type)`` before the per-class discriminators, so events differing in any
of those three can never collide.

Versioning
----------
:data:`EVENT_SIGNATURE_VERSION` prefixes every signature. Bump it whenever the
component recipe or a normalisation rule changes so that signatures generated by
different rule versions never silently compare equal.

Related operational signature rules
-----------------------------------
``resolution_signature.py`` defines the MSP-B4 incident identity/resolution
recipes. ``remediation_signature.py`` defines the MSP-B11 remediation-workflow
recipe: normalized vulnerability class, resolved CI class, and ordered
remediation state path. Each adjacent module documents its included, excluded,
and normalized fields under this same versioned ordered-component contract.
"""

from __future__ import annotations

import hashlib
from typing import Any, Dict, List, Optional, Tuple

#: Bump when the component recipe or any normalisation rule changes (see module
#: docstring). Part of the signature string so cross-version signatures differ.
EVENT_SIGNATURE_VERSION = "1"

#: Component field-separator (ASCII unit separator) — a control char that cannot
#: appear in a normalised component, so component boundaries are unambiguous and
#: ``["a", "b"]`` can never collide with ``["a\x1fb"]``.
_SEP = "\x1f"

#: The provider families the signature rules recognise.
PROVIDER_FAMILIES: frozenset = frozenset({"aws", "azure", "event_bridge", "generic"})

#: Map a raw ``source_system`` (alphanumeric-folded) onto a provider family. A
#: source system not listed here falls back to ``"generic"``.
_SOURCE_SYSTEM_FAMILY: Dict[str, str] = {
    "aws": "aws",
    "awscloudtrail": "aws",
    "awscloudwatch": "aws",
    "cloudtrail": "aws",
    "cloudwatch": "aws",
    "azure": "azure",
    "azuremonitor": "azure",
    "azureactivity": "azure",
    "azureactivitylog": "azure",
    # 2.0-D3: Application Insights signals are Azure signals. Registering the
    # family here is what makes an App Insights event's signature comparable with
    # every other Azure event's — without it the source system would fall back to
    # "generic" and the same recurring fault would fingerprint differently
    # depending on which Azure surface reported it.
    "azureappinsights": "azure",
    "eventbridge": "event_bridge",
    "eventhistorybridge": "event_bridge",
    "eventhistory": "event_bridge",
    "bridge": "event_bridge",
}

#: Per-event-class recipe: the ordered discriminators appended after the
#: always-present ``(family, event_class, resource_type)`` prefix. ``event_type``
#: and ``resource`` identify the recurring event; ``principal`` distinguishes the
#: actor for access/audit/security events. Unlisted classes use ``_DEFAULT_RECIPE``.
_DEFAULT_RECIPE: Tuple[str, ...] = ("event_type", "resource")
_CLASS_RECIPE: Dict[str, Tuple[str, ...]] = {
    "lifecycle": ("event_type", "resource"),
    "configuration": ("event_type", "resource"),
    "state_change": ("event_type", "resource"),
    "error": ("event_type", "resource"),
    "performance": ("event_type", "resource"),
    "access": ("event_type", "resource", "principal"),
    "audit": ("event_type", "resource", "principal"),
    "security": ("event_type", "resource", "principal"),
    "other": ("event_type", "resource"),
}


def provider_family(source_system: Optional[str]) -> str:
    """Resolve a ``source_system`` id to one of :data:`PROVIDER_FAMILIES`.

    Case- and separator-insensitive (``"AWS-CloudTrail"`` → ``"aws"``); an
    unrecognised source falls back to ``"generic"`` so the signature is always
    computable.
    """
    key = "".join(ch for ch in str(source_system or "").lower() if ch.isalnum())
    return _SOURCE_SYSTEM_FAMILY.get(key, "generic")


def _normalize_event_type(family: str, event_type: Optional[str]) -> str:
    """Fold a provider-native event name to one canonical token, per family.

    * ``aws`` — space-delimited titles → lower snake (whitespace runs → ``_``).
    * ``azure`` — slash-path operation ids → lowercased, slashes preserved,
      whitespace runs → ``_``.
    * ``event_bridge`` / ``generic`` — lowercased, whitespace runs → ``_``.
    """
    et = str(event_type or "").strip().lower()
    if not et:
        return ""
    # All families collapse internal whitespace to a single underscore; Azure's
    # rule is identical except that its '/' path separators are meaningful and
    # left intact (they survive because they are not whitespace).
    return "_".join(et.split())


def _normalize_resource_key(resource_id: Optional[str]) -> str:
    """Fold a provider-native resource id (ARN / resource URI) to a stable key.

    Lower-cased and stripped so trivial casing/whitespace differences in the same
    resource id do not fragment recurrence. Empty when the event concerns no
    specific resource.
    """
    return str(resource_id or "").strip().lower()


def _canonical_token(value: Optional[str]) -> str:
    return str(value or "").strip().lower()


def compute_event_signature(
    *,
    source_system: str,
    event_class: str,
    resource_type: str,
    event_type: str,
    resource_id: Optional[str] = None,
    principal: Optional[str] = None,
) -> str:
    """Construct the deterministic ``event_signature`` for an operational event.

    Follows the documented mapping contract (module docstring): builds the
    ordered component list for the event's provider family + class, then hashes
    it. Pure function of its inputs — no clock, no randomness — so repeated
    occurrences of the same recurring event always yield the identical signature
    (T2-AC1) while any change to a participating component changes it (T2-AC2).
    """
    family = provider_family(source_system)
    # Always-present prefix — events differing in family/class/resource_type can
    # never collide regardless of the per-class recipe.
    components: List[str] = [
        family,
        _canonical_token(event_class),
        _canonical_token(resource_type),
    ]
    available = {
        "event_type": _normalize_event_type(family, event_type),
        "resource": _normalize_resource_key(resource_id),
        "principal": _canonical_token(principal),
    }
    for key in _CLASS_RECIPE.get(_canonical_token(event_class), _DEFAULT_RECIPE):
        components.append(available.get(key, ""))

    joined = _SEP.join(components)
    digest = hashlib.sha256(joined.encode("utf-8")).hexdigest()[:32]  # 128-bit
    return f"{EVENT_SIGNATURE_VERSION}:{digest}"


def signature_components(
    *,
    source_system: str,
    event_class: str,
    resource_type: str,
    event_type: str,
    resource_id: Optional[str] = None,
    principal: Optional[str] = None,
) -> Dict[str, Any]:
    """Return the resolved components behind a signature (debug/audit aid).

    Exposes exactly what :func:`compute_event_signature` hashes so a caller can
    explain *why* two events share (or differ in) a signature, without
    re-deriving the rules.
    """
    family = provider_family(source_system)
    recipe = _CLASS_RECIPE.get(_canonical_token(event_class), _DEFAULT_RECIPE)
    return {
        "version": EVENT_SIGNATURE_VERSION,
        "provider_family": family,
        "event_class": _canonical_token(event_class),
        "resource_type": _canonical_token(resource_type),
        "recipe": list(recipe),
        "event_type_normalized": _normalize_event_type(family, event_type),
        "resource_key": _normalize_resource_key(resource_id),
        "principal": _canonical_token(principal),
    }
