"""
run_reproducibility.py — 2.0-D4 T3: the per-run version record.

The question this answers is one nobody asks until six months later, which is why it
is easy to under-build:

    "This run produced these findings. Today's run of apparently the same data
     produces different ones. What changed?"

Without a per-run version record the answer needs archaeology across git history,
and in a regulated context "we think the pack changed" is not an answer.

What this is NOT
----------------
D4-AC4 asks for a record "sufficient for reproducibility EXPLANATION", not
sufficient for byte-identical replay. Stated plainly here to stop scope drift:
replay in this platform re-serves persisted artifacts and deliberately does not
re-run ingestion or regenerate LLM output (see the replay contract in CLAUDE.md),
and this record does not attempt to change that.

What it must support is a HUMAN explanation. Given an old run and a new one, a
support engineer should be able to point at exactly which of pack version,
connector version, assembly policy or AI mode differs and say "that is why".
:func:`diff_reproducibility` is that comparison, and it is deliberately the shape a
customer will eventually want in the UI.

The four dimensions
-------------------
**Packs — already existed; not rebuilt.** ``discovery/runner.py`` stamps ``packIds``
and ``materialize_t2.py`` carries ``packIds`` / ``packVersions`` / a fuller ``packs``
execution block onto the run record. This module READS that rather than recomputing
it, so there is one source of truth. The 1.9 discipline behind it — bump
``packVersion`` whenever a pack's detector, scorer or corroboration logic changes —
is what makes the stamp meaningful; ``tests/contract/test_run_reproducibility.py``
verifies every registered pack declares a version rather than assuming it.

**AI mode — the most consequential, and the easiest.** ``MODEL_GENERATION_PROVIDER``
and ``MODEL_EMBEDDING_PROVIDER`` resolve INDEPENDENTLY, so both are recorded rather
than one collapsed "AI mode". That is not pedantry: the shipped configuration
deliberately mixes them (embeddings via ``customer_tenant``, generation via
``hosted``), so a single field would be wrong for the default deployment. A run
whose narrative came from a customer's in-tenant model is a genuinely different
artifact from one generated by the hosted provider. The active embedding model
identity is recorded alongside, because R18-B1 already stamps
``(embedding_model, embedding_model_version)`` per vector precisely so a deployment
rename does not invalidate an index — the same reasoning applies here.

**Connector versions — a definition problem before an implementation problem.** A
SaaS connector has no version in the sense a pack does. What actually varies is:

  * the remote API version negotiated (Salesforce ``v59.0``, Jira ``3``, ServiceNow
    ``v1``, the Azure ``api-version`` dates) — declared per ingestor module;
  * the ingestor's own code; and
  * the auth mode in use.

The failure mode to avoid is a field that always reads ``1.0.0`` and therefore
explains nothing — **a version that never changes is worse than an absent field,
because it invites false confidence.** So the ingestor's code identity is a
FINGERPRINT derived from its source rather than a hand-maintained version string
nobody remembers to bump. A source fingerprint cannot go stale by construction:
change the ingestor, and the value changes.

The trade-off, stated rather than hidden: a comment-only edit also changes the
fingerprint, so the diff can report a change that altered no behaviour. For this
question that is the right direction to err — a false positive says "the ingestor
code moved, look at it", while a never-bumped version says nothing at all and is
believed.

**Assembly policy — honest about what does not exist yet.** A policy *version*
belongs to 2.0-B3, which declares assembly precedence as explicit configuration. B3
has not landed: ``app.context_assembly.AssemblyPolicy`` exists as a frozen dataclass
with concrete defaults, and carries no version. So ``version`` is recorded as
``None`` with a documented reason — the posture 2.0-A1 took for findings created
before projections shipped — rather than inventing a placeholder. A record that
claims to know something it does not is exactly the failure this story exists to
prevent.

But ``None`` alone would be less useful than the truth available, so the EFFECTIVE
policy values are recorded too, with a fingerprint over them. Those are what
actually change behaviour: if ``confidence_floor`` moves from 0.0 to 0.3 the diff
shows it, whereas a version integer only helps if somebody bumped it. When B3 lands
it should populate ``version`` and keep the effective block.
"""
from __future__ import annotations

import hashlib
import inspect
import json
import logging
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)

#: Record-format version. Bump when the SHAPE changes, so a consumer comparing two
#: runs can tell "the record format changed" from "the platform changed".
REPRODUCIBILITY_RECORD_VERSION = "1"

#: Why ``assembly_policy.version`` is null. Recorded IN the record, so a reader six
#: months from now does not have to find this module to understand the gap.
ASSEMBLY_POLICY_VERSION_ABSENT_REASON = (
    "assembly policy versioning is 2.0-B3 (assembly precedence as explicit "
    "configuration), which has not landed. AssemblyPolicy exists but declares no "
    "version, so this is null rather than a placeholder; the effective policy "
    "values below are recorded instead, since those are what change behaviour."
)

#: Length of a truncated sha256 fingerprint. Long enough that a collision is not a
#: practical concern for this purpose, short enough to read in a diff.
_FINGERPRINT_CHARS = 16


def _fingerprint(value: Any) -> str:
    """A short, stable content fingerprint. Deterministic across processes."""
    if isinstance(value, (bytes, bytearray)):
        raw = bytes(value)
    elif isinstance(value, str):
        raw = value.encode("utf-8")
    else:
        raw = json.dumps(value, sort_keys=True, separators=(",", ":")).encode("utf-8")
    return hashlib.sha256(raw).hexdigest()[:_FINGERPRINT_CHARS]


# ── packs (read the existing stamp; never recompute it) ────────────────────────


def pack_record(run: Optional[Dict[str, Any]]) -> Dict[str, Any]:
    """The pack half of the record, read from what the run already carries.

    Deliberately a READ. ``materialize_t2`` already stamps ``packIds`` /
    ``packVersions`` / ``packs``; recomputing them here would create a second source
    of truth that could disagree with the findings' own ``packId``/``packVersion``
    stamps — and a reproducibility record that disagrees with the artifacts it
    describes is worse than none.
    """
    run = run or {}
    pack_ids: List[str] = [str(p) for p in (run.get("packIds") or []) if str(p).strip()]
    versions = run.get("packVersions") or {}
    if not isinstance(versions, dict):
        versions = {}

    # Fall back to the backward-compatible singular scalars (R191-P1 keeps them
    # mirroring the primary pack) so a pre-multi-pack run still yields a record.
    if not pack_ids and run.get("packId"):
        pack_ids = [str(run["packId"])]
    if not versions and run.get("packId") and run.get("packVersion"):
        versions = {str(run["packId"]): str(run["packVersion"])}

    return {
        "pack_ids": pack_ids,
        "pack_versions": {str(k): str(v) for k, v in versions.items()},
        # A pack selected but carrying no version is a real gap, surfaced rather
        # than silently absent from the map.
        "packs_missing_version": sorted(
            p for p in pack_ids if p not in {str(k) for k in versions}
        ),
    }


# ── AI mode (both providers, independently) ────────────────────────────────────


def ai_mode_record() -> Dict[str, Any]:
    """Which model providers served this run, and the embedding model identity.

    Both providers, never one collapsed "AI mode": they resolve independently and
    the shipped configuration deliberately mixes them.
    """
    generation: Optional[str] = None
    embedding: Optional[str] = None
    try:
        from .model_gateway import resolve_provider_names

        generation, embedding = resolve_provider_names()
    except Exception:  # noqa: BLE001 — a version record must never break a run
        logger.debug("reproducibility: provider names unavailable", exc_info=True)

    model_identity: Optional[str] = None
    model_version: Optional[str] = None
    try:
        from .retrieval.embedder import active_embedding_model

        model_identity, model_version = active_embedding_model()
    except Exception:  # noqa: BLE001
        logger.debug("reproducibility: embedding model identity unavailable", exc_info=True)

    return {
        "generation_provider": generation,
        "embedding_provider": embedding,
        # R18-B1 stamps this per vector so a deployment rename does not invalidate
        # the index; the same identity is what makes an old run's embeddings
        # comparable with a new one's.
        "embedding_model": model_identity,
        "embedding_model_version": model_version,
    }


# ── connectors ────────────────────────────────────────────────────────────────

#: connector id -> the ingest module whose code and API version describe it.
#: Explicit rather than discovered, so an unmapped connector is visibly unmapped
#: instead of silently reported as "no version available".
CONNECTOR_INGEST_MODULES: Dict[str, str] = {
    "salesforce": "discovery.ingest.salesforce",
    "salesforce_fsc": "discovery.ingest.fsc",
    "ncino": "discovery.ingest.ncino",
    "strs": "discovery.ingest.strs_benefits",
    "servicenow": "discovery.ingest.servicenow",
    "jira": "discovery.ingest.jira",
    "confluence": "discovery.ingest.confluence",
    "slack": "discovery.ingest.slack",
    "teams": "discovery.ingest.teams",
    "sharepoint": "discovery.ingest.sharepoint",
    "github": "discovery.ingest.git_content",
    "java_app": "discovery.ingest.java_app",
    "dotnet_app": "discovery.ingest.dotnet_app",
    "documents": "discovery.ingest.documents",
    "aws_events": "discovery.ingest.aws_event_connector",
    "azure_events": "discovery.ingest.azure_events",
}


#: The module-level constant names ingestors actually use for the remote API version.
#: An explicit list rather than ``API_VERSION`` alone, because the connectors do not
#: agree on a name — Salesforce/FSC/nCino/STRS use ``API_VERSION`` while Jira uses
#: ``JIRA_API_VERSION`` and ServiceNow ``SN_API_VERSION``. Assuming one name silently
#: reported ServiceNow's version as absent, which is exactly the quiet-wrong-answer
#: failure this record is supposed to eliminate, so
#: ``test_every_declared_api_version_is_discovered`` now pins the list against the
#: source tree and fails if a connector introduces a name that is not here.
_API_VERSION_ATTRS = (
    "API_VERSION",
    "JIRA_API_VERSION",
    "SN_API_VERSION",
    "GRAPH_API_VERSION",
    "ALERTS_API_VERSION",
    "ACTIVITY_LOG_API_VERSION",
    "SERVICE_HEALTH_API_VERSION",
)


#: Connectors whose remote API version lives in a SIBLING client module rather than
#: the connector itself. The Azure connector pins one api-version per ARM surface in
#: azure_alerts / azure_admin_events, so reading only azure_events.py reported None —
#: a null where the platform demonstrably does pin a version is the "explains
#: nothing" weakness this record exists to avoid.
CONNECTOR_VERSION_MODULES: Dict[str, tuple] = {
    "azure_events": ("discovery.ingest.azure_alerts", "discovery.ingest.azure_admin_events"),
}


def _api_versions_of(module) -> Dict[str, str]:
    """The ``{constant: value}`` API versions a module declares."""
    return {
        attr: str(getattr(module, attr))
        for attr in _API_VERSION_ATTRS
        if getattr(module, attr, None) not in (None, "")
    }


def _format_api_version(found: Dict[str, str]) -> Optional[str]:
    """Render the discovered versions.

    A single version reads as the bare value (``v59.0``) — naming the constant would
    be noise. Several read as sorted ``name=value`` pairs, because a connector that
    negotiates one api-version per surface genuinely has several and collapsing them
    would hide which surface moved.

    ``None`` when the connector pins none: a document scan or a native DB connector
    has no remote API version, and a fabricated default is worse than a missing one.
    """
    if not found:
        return None
    if len(found) == 1:
        return next(iter(found.values()))
    return "; ".join(f"{name}={value}" for name, value in sorted(found.items()))


def _module_code_fingerprint(module) -> Optional[str]:
    """A fingerprint of the ingestor's SOURCE.

    Deliberately not a hand-maintained version string: a version nobody bumps always
    reads the same and therefore explains nothing, which is worse than an absent
    field because it invites false confidence. A source fingerprint cannot go stale.
    """
    try:
        return _fingerprint(inspect.getsource(module))
    except Exception:  # noqa: BLE001 — a missing source is reported, never fatal
        return None


def connector_record(
    org_id: Optional[str],
    connector_ids: Optional[List[str]] = None,
) -> Dict[str, Any]:
    """Per-connector version identity for the connectors this run used.

    Each entry carries the three things that ACTUALLY vary for a SaaS connector:
    the remote ``api_version``, the ingestor's ``code_fingerprint``, and the
    ``auth_mode`` in use. None of them is a constant nobody updates.
    """
    import importlib

    ids = [str(c) for c in (connector_ids or []) if str(c).strip()]
    out: Dict[str, Any] = {}
    unmapped: List[str] = []

    for connector_id in sorted(set(ids)):
        module_name = CONNECTOR_INGEST_MODULES.get(connector_id)
        if module_name is None:
            unmapped.append(connector_id)
            continue
        entry: Dict[str, Any] = {"ingest_module": module_name}
        try:
            module = importlib.import_module(module_name)
        except Exception:  # noqa: BLE001
            entry["api_version"] = None
            entry["code_fingerprint"] = None
            entry["unavailable"] = "ingest module could not be imported"
            out[connector_id] = entry
            continue
        # API versions: the connector's own module, plus any sibling client module
        # that pins one (see CONNECTOR_VERSION_MODULES).
        found = _api_versions_of(module)
        for sibling in CONNECTOR_VERSION_MODULES.get(connector_id, ()):
            try:
                found.update(_api_versions_of(importlib.import_module(sibling)))
            except Exception:  # noqa: BLE001 — a missing sibling is reported as absent
                logger.debug(
                    "reproducibility: version module %s unavailable", sibling,
                    exc_info=True,
                )
        entry["api_version"] = _format_api_version(found)
        entry["code_fingerprint"] = _module_code_fingerprint(module)
        entry["auth_mode"] = _auth_mode(org_id, connector_id)
        out[connector_id] = entry

    return {
        "connectors": out,
        # Visibly unmapped rather than silently missing: an unmapped connector means
        # CONNECTOR_INGEST_MODULES needs an entry, which is a real finding.
        "unmapped": sorted(unmapped),
    }


def _auth_mode(org_id: Optional[str], connector_id: str) -> Optional[str]:
    """The auth mode in use for this org+connector, or ``None`` when unknown."""
    if not org_id:
        return None
    try:
        from .auth.auth_modes import resolve_auth_mode

        return str(resolve_auth_mode(str(org_id), connector_id))
    except Exception:  # noqa: BLE001 — no DB / not configured => unknown, not a crash
        logger.debug(
            "reproducibility: auth mode unavailable for %s", connector_id, exc_info=True
        )
        return None


# ── assembly policy ───────────────────────────────────────────────────────────


def assembly_policy_record(policy: Any = None) -> Dict[str, Any]:
    """The assembly-policy half — honest about the version that does not exist.

    ``version`` is ``None`` with a recorded reason (2.0-B3 has not landed), and the
    EFFECTIVE values are captured alongside because those are what actually change
    behaviour. When B3 lands it should populate ``version`` and keep ``effective``.
    """
    effective: Optional[Dict[str, Any]] = None
    try:
        if policy is None:
            from .context_assembly import AssemblyPolicy

            policy = AssemblyPolicy()
        effective = {
            field: getattr(policy, field)
            for field in sorted(getattr(policy, "__dataclass_fields__", {}))
        }
    except Exception:  # noqa: BLE001
        logger.debug("reproducibility: assembly policy unavailable", exc_info=True)

    return {
        "version": None,
        "version_absent_reason": ASSEMBLY_POLICY_VERSION_ABSENT_REASON,
        "effective": effective,
        "effective_fingerprint": _fingerprint(effective) if effective else None,
    }


# ── the record ────────────────────────────────────────────────────────────────


def build_reproducibility_record(
    run: Optional[Dict[str, Any]] = None,
    *,
    org_id: Optional[str] = None,
    connector_ids: Optional[List[str]] = None,
) -> Dict[str, Any]:
    """The per-run version record (D4-AC4).

    Every dimension degrades to ``None``/empty with a reason rather than raising: a
    version record exists to explain a run, and it must never be the reason a run
    fails.
    """
    run = run or {}
    return {
        "record_version": REPRODUCIBILITY_RECORD_VERSION,
        "packs": pack_record(run),
        "connectors": connector_record(org_id, connector_ids),
        "assembly_policy": assembly_policy_record(),
        "ai_mode": ai_mode_record(),
    }


# ── the comparison (what AC4 actually asks for) ───────────────────────────────

#: Human-readable dimension labels, so a diff reads as an explanation rather than a
#: set of dotted paths.
_DIMENSION_LABELS = {
    "packs": "pack versions",
    "connectors": "connector versions",
    "assembly_policy": "assembly policy",
    "ai_mode": "AI mode",
}


def _flatten(value: Any, prefix: str = "") -> Dict[str, Any]:
    """Flatten a nested record to ``dotted.path -> scalar`` for comparison."""
    out: Dict[str, Any] = {}
    if isinstance(value, dict):
        for key in sorted(value):
            out.update(_flatten(value[key], f"{prefix}.{key}" if prefix else str(key)))
    elif isinstance(value, (list, tuple)):
        out[prefix] = json.dumps(list(value), sort_keys=True, default=str)
    else:
        out[prefix] = value
    return out


def diff_reproducibility(
    older: Optional[Dict[str, Any]],
    newer: Optional[Dict[str, Any]],
) -> Dict[str, Any]:
    """Compare two reproducibility records and explain what changed.

    This is the deliverable AC4 is really asking for: given an old run and a new
    one, a support engineer must be able to point at exactly which dimension differs
    and say "that is why". Also, not incidentally, the shape a customer will want in
    the UI.

    ``version_absent_reason`` is excluded from comparison — it is explanatory prose,
    not a version, and a wording change is not a platform change.
    """
    older = older or {}
    newer = newer or {}
    flat_old = _flatten(older)
    flat_new = _flatten(newer)

    changes: List[Dict[str, Any]] = []
    for path in sorted(set(flat_old) | set(flat_new)):
        if path.endswith("version_absent_reason"):
            continue
        before = flat_old.get(path)
        after = flat_new.get(path)
        if before == after:
            continue
        changes.append({
            "dimension": _DIMENSION_LABELS.get(path.split(".")[0], path.split(".")[0]),
            "field": path,
            "before": before,
            "after": after,
        })

    dimensions_changed = sorted({c["dimension"] for c in changes})
    return {
        "identical": not changes,
        "dimensions_changed": dimensions_changed,
        "changes": changes,
        "summary": _summarise(dimensions_changed, changes),
    }


def _summarise(dimensions: List[str], changes: List[Dict[str, Any]]) -> str:
    """One readable sentence — the answer to "what changed?"."""
    if not changes:
        return (
            "No recorded version difference: pack versions, connector versions, "
            "assembly policy and AI mode are identical for both runs. A difference "
            "in findings is therefore explained by the DATA, not by the platform."
        )
    listed = ", ".join(dimensions)
    return (
        f"{len(changes)} recorded difference(s) across {len(dimensions)} "
        f"dimension(s): {listed}. A difference in findings between these runs may "
        f"be explained by these changes rather than by the data."
    )
