from __future__ import annotations

import os
from typing import Optional
from urllib.parse import urlencode

import httpx

from app.auth.models import ConnectorAuthConfig
from app.auth.secrets import resolve_secret

OAUTH_HTTP_TIMEOUT = int(os.environ.get("OAUTH_HTTP_TIMEOUT_SECONDS", "30"))


class OAuthError(Exception):
    """Raised when an OAuth HTTP call fails.

    Never includes upstream response body or secret values.
    """

    def __init__(self, connector_id: str, reason: str | int) -> None:
        self.connector_id = connector_id
        self.reason = reason
        super().__init__(f"OAuth error for connector '{connector_id}': {reason}")


def build_auth_url(
    config: ConnectorAuthConfig,
    state: str,
) -> str:
    """Build the authorization URL to redirect the user to the OAuth provider.

    `state` is a CSRF nonce generated by the caller (T8).
    Does not call resolve_secret — client_secret is not needed at this step.
    Raises ValueError if the config has no authorization_url (e.g. client_credentials flow).
    """
    if not config.authorization_url:
        raise ValueError(
            f"Connector '{config.connector_id}' has no authorization_url "
            "(client_credentials flows do not use a browser redirect)"
        )
    params = {
        "client_id": config.client_id,
        "redirect_uri": config.redirect_uri,
        "scope": " ".join(config.scopes),
        "state": state,
        "response_type": "code",
    }
    return f"{config.authorization_url}?{urlencode(params)}"


async def exchange_code(
    config: ConnectorAuthConfig,
    code: str,
    *,
    _transport: Optional[httpx.AsyncBaseTransport] = None,
) -> dict:
    """Exchange an authorization code for an access token.

    _transport is injected only in tests; callers omit it.
    Secret is resolved inline and discarded when the async-with block exits.
    """
    async with httpx.AsyncClient(timeout=OAUTH_HTTP_TIMEOUT, transport=_transport) as client:
        try:
            response = await client.post(
                config.token_url,
                data={
                    "grant_type": "authorization_code",
                    "code": code,
                    "client_id": config.client_id,
                    "client_secret": resolve_secret(config.secret_key),
                    "redirect_uri": config.redirect_uri,
                },
            )
        except httpx.TimeoutException:
            raise OAuthError(config.connector_id, "timeout")
    if response.status_code != 200:
        raise OAuthError(config.connector_id, response.status_code)
    return response.json()


async def refresh_token(
    config: ConnectorAuthConfig,
    refresh_token_value: str,
    *,
    _transport: Optional[httpx.AsyncBaseTransport] = None,
) -> dict:
    """Exchange a refresh token for a new access token.

    _transport is injected only in tests; callers omit it.
    Secret is resolved inline and discarded when the async-with block exits.
    """
    async with httpx.AsyncClient(timeout=OAUTH_HTTP_TIMEOUT, transport=_transport) as client:
        try:
            response = await client.post(
                config.token_url,
                data={
                    "grant_type": "refresh_token",
                    "refresh_token": refresh_token_value,
                    "client_id": config.client_id,
                    "client_secret": resolve_secret(config.secret_key),
                },
            )
        except httpx.TimeoutException:
            raise OAuthError(config.connector_id, "timeout")
    if response.status_code != 200:
        raise OAuthError(config.connector_id, response.status_code)
    return response.json()


async def get_client_credentials_token(
    config: ConnectorAuthConfig,
    *,
    _transport: Optional[httpx.AsyncBaseTransport] = None,
) -> dict:
    """Fetch a token using the client_credentials flow (SAP, D365).

    _transport is injected only in tests; callers omit it.
    Secret is resolved inline and discarded when the async-with block exits.
    """
    async with httpx.AsyncClient(timeout=OAUTH_HTTP_TIMEOUT, transport=_transport) as client:
        try:
            response = await client.post(
                config.token_url,
                data={
                    "grant_type": "client_credentials",
                    "client_id": config.client_id,
                    "client_secret": resolve_secret(config.secret_key),
                    "scope": " ".join(config.scopes),
                },
            )
        except httpx.TimeoutException:
            raise OAuthError(config.connector_id, "timeout")
    if response.status_code != 200:
        raise OAuthError(config.connector_id, response.status_code)
    return response.json()
